name: Order Service Test

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    setup-and-build:
        strategy:
            matrix:
                directory:
                    - 'order-service'

        runs-on: ubuntu-latest
        name: Setup and Build
        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v1

            - name: Install dependencies
              run: bun install --frozen-lockfile
              working-directory: ${{ matrix.directory }}

            - name: Run Tests
              run: bun test
              working-directory: ${{ matrix.directory }}

            - uses: reviewdog/action-eslint@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  reporter: github-pr-review
                  workdir: ${{ matrix.directory }}

